routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function (){
    return Redirect::to('/home');
});

Route::prefix('dashboard')->group(function () {
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
});
Route::namespace('Admin')
->prefix('dashboard')
->middleware('auth')
->group(function () {
    Route::resource('organizers', OrganizerController::class);
    Route::resource('data-entry', DataEntryController::class);
    Route::resource('users', UserController::class);
    Route::resource('palyers', PlayerController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('news', NewsController::class);


    Route::resource('events', EventController::class);
    Route::get('show_teams/{event_id}', 'EventController@showTeams')->name('event.show.team');
    Route::post('add_teams', 'EventController@addTeams')->name('event.add.team');

    Route::resource('teams', TeamController::class);
    Route::get('show_players/{team_id}', 'TeamController@showPlayers')->name('team.show.player');
    Route::post('add_players', 'TeamController@addPlayers')->name('team.add.player');

});

Route::namespace('Website')
->group(function () {

    Route::get('{slug}', PageController::class);
    Route::get('event/category/{slug}', 'PageController@eventByCategory')->name('event.by.category.page');
    Route::get('event/{id}/detail', 'PageController@eventDetail')->name('event.detail.page');

    Route::get('show_event/{id}', 'PageController@eventCategoryPage')->name('event.category.page');
    Route::get('show_news/{id}', 'PageController@showNews')->name('show.news.detail.page');

    Route::post('/new/register', PublicRegisterController::class)->name('website.post');
    Route::post('/new/Login', PublicLoginController::class)->name('website.login');

    Route::get('ticket/{event_id}', 'TicketController@ticket')->name('ticket');
    Route::post('ticket', 'TicketController@ticketPost')->name('ticket.post');

});

// clientdashboard and organizer
// Route::group(['middleware' => 'auth'],function () {
//     Route::get('/userdashboard', function () {
//         return view('website.clientDashboard.index');
//     })->name('userdashboard');

// });
Route::namespace('ClientDashboard')
 ->middleware(['auth'])
 ->as('userdashboard.')
 ->prefix('userdashboard')
 ->group(function(){
     Route::get('/home', HomeController::class)->name('home');
     Route::resource('editUserInfo', UserEditController::class);

 });

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    protected $fillable = [
    'avtar','team_name','email','phone','country','city','state'
    ];
}

app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Services\FileUploadService;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\TeamHavePlayer;
use App\Team;
use App\Player;
use Auth;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teams=Team::latest()->get();
        return  view('admin.team.index',compact('teams'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.team.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            'team_name' => 'required',
            'email' => 'required|email|unique:player',
            'phone' => 'required',
            'country' => 'required',
            'city' => 'required',
            'state' => 'required',
         ]);

        $file = FileUploadService::upload( $request->file('avtar'), 'public/team' );


         $team = new Team;
         $team->organizer_id = Auth::user()->id;
         $team->team_name = $request->team_name;
         $team->email  = $request->email;
         $team->avtar =$file->uploaded_name;
         $team->phone = $request->phone;
         $team->country = $request->country;
         $team->city = $request->city;
         $team->state = $request->state;

         $team->save();


         $request->session()->flash('msg','Record successfully inserted');
         return redirect()->route('teams.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $team=Team::find($id);
        return view('admin.team.show',compact('team'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $team=Team::find($id);
        return view('admin.team.edit',['team'=>$team]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        if ($request->hasFile('avtar') && $request->file('avtar')) {
            $validateData = $request->validate([
                'team_name' => 'required',
                'email' => ['required',
                Rule::unique('player')->ignore($id)],
                'phone' => 'required',
                'country' => 'required',
                'city' => 'required',
                'state' => 'required',
             ]);

             $file = FileUploadService::upload( $request->file('avtar'), 'public/team' );

             $team =Team::find($id);
             $team->team_name = $request->team_name;
             $team->avtar =$file->uploaded_name;
             $team->email  = $request->email;
             $team->phone = $request->phone;
             $team->country = $request->country;
             $team->city = $request->city;
             $team->state = $request->state;
             $team->save();
             return  redirect()->route('teams.index');
        }else{
            $validateData = $request->validate([
                'team_name' => 'required',
                'email' => ['required',
                Rule::unique('player')->ignore($id)],
                'phone' => 'required',
                'country' => 'required',
                'city' => 'required',
                'state' => 'required',
             ]);


             $team =Team::find($id);
             $team->team_name = $request->team_name;
             $team->email  = $request->email;
             $team->phone = $request->phone;
             $team->country = $request->country;
             $team->city = $request->city;
             $team->state = $request->state;
             $team->save();
             return  redirect()->route('teams.index');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = TeamHavePlayer::where('team_id', $id)->get();
        if($data !== null){
            foreach ($data as $key => $team) {
                # code...
                $d = TeamHavePlayer::where('id', $team->id)->first();
                $d->delete();
            }
        }
        $team=Team::find($id);
        $team->delete();
        if ($team != null){
            $team->delete();
            session()->flash('msg','User Deleted Successfully');
        }

        return back();
    }

    public function showPlayers($team_id){

        $team = Team::find($team_id);
        $getExistingPlayers = TeamHavePlayer::where('team_id', $team_id)->get()->pluck('player_id')->toArray();
        $players = Player::where('organizer_id', Auth::user()->id)->whereNotIn('id', $getExistingPlayers)->latest()->get();
        return view('admin.team.selectPlayer',compact('team', 'players'));

    }

    public function addPlayers(Request $request){

        $validateData = $request->validate([
            'team_id' => 'required',
            'player' => 'required',
         ]);


        foreach ($_POST['player'] as $key => $value) {
            # code...
            $teamplayer = new TeamHavePlayer;
            $teamplayer->team_id = $request->team_id;
            $teamplayer->player_id = $value;
            $teamplayer->save();
        }

        return back();

    }
}

resources/views/admin/team/create.blade.php
@extends("layouts.admin.site")
@section("content")
<h4 class="font-weight-bold py-3 mb-4">
    Add Team <span class="text-muted"></span>
</h4>

<div class="nav-tabs-top">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#user-edit-account">Account</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="user-edit-account">
            <form action="{{ route('teams.store') }}" method="Post" enctype="multipart/form-data" >
                @csrf
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif


                </div>
                <hr class="border-light m-0">


                <div class="card-body pb-2">
                    <div class="media align-items-center">
                        <img src="{{ asset('assets/images/client-01.png') }}" id="change-avatar" alt="" class="d-block ui-w-80">
                        <div class="media-body ml-3">
                            <label class="form-label d-block mb-2">Avatar</label>
                            <label class="btn btn-outline-primary btn-sm">
                            Add
                                 <input type="file"  onchange="changeAvatar(this);" name="avtar" class="user-edit-fileinput d-none">
                            </label>&nbsp;

                        </div>
                    </div>
                    {{--  <div class="form-group">
                        <label class="form-label">Image</label>
                        <input type="file" name="avtar" required class="form-control mb-1" >
                    </div>  --}}

                <div class="form-group">
                    <label class="form-label"> Name</label>
                    <input type="text" name="team_name" class="form-control mb-1" placeholder="Team Name">
                </div>
                <div class="form-group">
                    <label class="form-label"> Email</label>
                    <input type="email" name="email" class="form-control" placeholder="Email">
                </div>
                <div class="form-group">
                    <label class="form-label">Phone</label>
                    <input type="tel"  name="phone" class="form-control" placeholder="Phone">
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label">Country</label>
                            <input type="text" name="country" class="form-control" value="Country">
                        </div>

                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label">City</label>
                            <input type="text" name="city" class="form-control" placeholder="City">
                        </div>

                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-label">State</label>
                            <input type="text" name="state" class="form-control" value="State">
                        </div>
                    </div>
                </div>


                <div class="text-right mt-3">
                    <button type="submit" class="btn btn-primary">Add</button>&nbsp;
                    <button type="button" class="btn btn-default">Cancel</button>
                </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function changeAvatar(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
              $('#change-avatar')
                  .attr('src', e.target.result)
                  .width(80)
                  .height(80);
          };
          reader.readAsDataURL(input.files[0]);
      }
  }
</script>
@endsection

resources/views/admin/team/edit.blade.php
@extends("layouts.admin.site")
@section("content")
<h4 class="font-weight-bold py-3 mb-4">
    Edit Event <span class="text-muted"></span>
</h4>

<div class="nav-tabs-top">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#user-edit-account">Account</a>
        </li>

    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="user-edit-account">
            <form action="{{ route('teams.update',$team->id) }}" method="Post" enctype="multipart/form-data" >
                    @csrf
                    @method('put')

                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                    <div class="media align-items-center">
                        <img src="{{ asset('storage/public/team/'.$team->avtar)}}" id="change-avatar" alt="" class="d-block ui-w-80">
                        <div class="media-body ml-3">
                            <label class="form-label d-block mb-2">Avatar</label>
                            <label class="btn btn-outline-primary btn-sm">
      Add
      <input type="file"  onchange="changeAvatar(this);" name="avtar"   class="user-edit-fileinput d-none">
    </label>&nbsp;

                        </div>
                    </div>

                </div>
                <hr class="border-light m-0">
                <div class="card-body pb-2">
                    <div class="form-group">
                        <label class="form-label"> Name</label>
                        <input type="text" name="team_name" class="form-control mb-1" value="{{ $team->team_name }}"  placeholder="team name">
                    </div>
                    <div class="form-group">
                        <label class="form-label"> Email</label>
                        <input type="email" name="email" class="form-control" value="{{ $team->email }}"  placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Phone</label>
                        <input type="tel"  name="phone" class="form-control" value="{{ $team->phone }}"  placeholder="Phone">
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">Country</label>
                                <input type="text" name="country" class="form-control" value="{{ $team->country }}" placeholder="Country">
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">City</label>
                                <input type="text" name="city" class="form-control" value="{{ $team->city }}"  placeholder="City">
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">State</label>
                                <input type="text" name="state" class="form-control" value="{{ $team->state }}" >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right mt-3">
                    <button type="submit" class="btn btn-primary">Save changes</button>&nbsp;
                    {{-- <button type="button" class="btn btn-default">Cancel</button> --}}
                </div>
            </form>

        </div>
    </div>
</div>
<script>
    function changeAvatar(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
              $('#change-avatar')
                  .attr('src', e.target.result)
                  .width(80)
                  .height(80);
          };
          reader.readAsDataURL(input.files[0]);
      }
  }
</script>

@endsection

resources/views/admin/team/index.blade.php
@extends('layouts.admin.site')
@section('content')
<h4 class="font-weight-bold py-3 mb-4">
    <span class="text-muted font-weight-light">Teams </span>
</h4>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('msg') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
 </div>
<!-- DataTable within card -->

<div class="card">

        <h6 class="card-header text-right">
            <a href="{{ route('teams.create') }}" class="btn btn-success" > Add New</a>
        </h6>

    <div class="card-datatable table-responsive">
        <table class="datatables-demo table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Team Name</th>
                    <th>Email</th>
                    <th>Player</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
              @isset($teams)
                  @if (count($teams)>0)
                        @foreach ($teams as $team)
                            <tr class="odd gradeX">
                                <td>{{ $team->id }}</td>
                                <td>{{ $team->team_name }}</td>
                                <td>{{ $team->email }}</td>
                                <td class="text-center">
                                    <a href="{{ route('team.show.player',$team->id) }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Add Player </a>
                                </td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-dark dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false">Action</button>
                                        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: top, left; top: 35px; left: 0px;">
                                            <a href="viewTeam.html" class="dropdown-item"><i class="fa fa-eye"></i> View  Profile</a>
                                            <a href="{{route('teams.edit',$team->id)}}" class="dropdown-item"><i class="fa fa-edit"></i> Edit </a>
                                            <form action="{{ route('teams.destroy',$team->id) }}" class="d-flex" method="post">
                                                @csrf
                                                <input type="hidden" name="_method" value="DELETE"> <button type="submit" class="dropdown-item">
                                        <i class="fa fa-trash"></i> Delete
                                      </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                  @else
                  <div class="m-3 text-center col-12">
                    <p>No Teams found...!</p>
                 </div>
                  @endif
              @endisset


            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/admin/team/selectPlayer.blade.php
@extends('layouts.admin.site')
@section('content')
<h4 class="font-weight-bold py-3 mb-4">
    <span class="text-muted font-weight-light">Teams </span>
</h4>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('msg') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
 </div>
<!-- DataTable within card -->

<div class="card">

        <h6 class="card-header text-right">
            <a href="#" class="btn btn-success" > Add New player</a>
        </h6>

    <div class="all player">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('team.add.player') }}" method="post">

            @csrf

            <input type="hidden" name="team_id" value="{{ $team->id ?? ''}}">

            @isset($players)
                @if (count($players) > 0)
                    @foreach ($players as $player)
                        <div class="form-check border-bottom p-3 pl-5">
                            <input class="form-check-input" name="player[]" type="checkbox" value="{{ $player->id ?? '' }}">
                            <label class="form-check-label" for="defaultCheck1">
                                {{ $player->player_name ?? '' }}
                            </label>
                        </div>
                    @endforeach
                @else
                    <p>No Player Found</p>
                @endif
            @endisset

            <div class="text-right mt-3 mb-3 mr-3">
                <button type="submit" class="btn btn-primary">Add player</button>&nbsp;
                {{-- <button type="button" class="btn btn-default">Cancel</button> --}}
            </div>

    </form>

    </div>
</div>
@endsection

resources/views/admin/team/show.blade.php
@extends("layouts.admin.site")
@section("content")
<div class="media align-items-center py-3 mb-3">
    <img src="assets/img/avatars/5-small.png" alt="" class="d-block ui-w-100 rounded-circle">
    <div class="media-body ml-4">
        <h4 class="font-weight-bold mb-0">Nelle Maxwell <span class="text-muted font-weight-normal">@nmaxwell</span></h4>
        <div class="text-muted mb-2">ID: 3425433</div>
        <a href="javascript:void(0)" class="btn btn-primary btn-sm">Edit</a>&nbsp;
        <a href="javascript:void(0)" class="btn btn-default btn-sm">Profile</a>&nbsp;
        <a href="javascript:void(0)" class="btn btn-default btn-sm icon-btn"><i class="ion ion-md-mail"></i></a>
    </div>
</div>


<div class="card">

    <div class="card-body">

        <table class="table user-view-table m-0">
            <tbody>

                <tr>
                    <td>Player Name:</td>
                    <td>xyz</td>
                </tr>

                <tr>
                    <td>Location:</td>
                    <td>xyz</td>
                </tr>

            </tbody>
        </table>

    </div>
</div>
@endsection