routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function (){
    return Redirect::to('/home');
});

Route::prefix('dashboard')->group(function () {
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
});
Route::namespace('Admin')
->prefix('dashboard')
->middleware('auth')
->group(function () {
    Route::resource('organizers', OrganizerController::class);
    Route::resource('data-entry', DataEntryController::class);
    Route::resource('users', UserController::class);
    Route::resource('palyers', PlayerController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('news', NewsController::class);


    Route::resource('events', EventController::class);
    Route::get('show_teams/{event_id}', 'EventController@showTeams')->name('event.show.team');
    Route::post('add_teams', 'EventController@addTeams')->name('event.add.team');

    Route::resource('teams', TeamController::class);
    Route::get('show_players/{team_id}', 'TeamController@showPlayers')->name('team.show.player');
    Route::post('add_players', 'TeamController@addPlayers')->name('team.add.player');

});

Route::namespace('Website')
->group(function () {

    Route::get('{slug}', PageController::class);
    Route::get('event/category/{slug}', 'PageController@eventByCategory')->name('event.by.category.page');
    Route::get('event/{id}/detail', 'PageController@eventDetail')->name('event.detail.page');

    Route::get('show_event/{id}', 'PageController@eventCategoryPage')->name('event.category.page');
    Route::get('show_news/{id}', 'PageController@showNews')->name('show.news.detail.page');

    Route::post('/new/register', PublicRegisterController::class)->name('website.post');
    Route::post('/new/Login', PublicLoginController::class)->name('website.login');

    Route::get('ticket/{event_id}', 'TicketController@ticket')->name('ticket');
    Route::post('ticket', 'TicketController@ticketPost')->name('ticket.post');

});

// clientdashboard and organizer
// Route::group(['middleware' => 'auth'],function () {
//     Route::get('/userdashboard', function () {
//         return view('website.clientDashboard.index');
//     })->name('userdashboard');

// });
Route::namespace('ClientDashboard')
 ->middleware(['auth'])
 ->as('userdashboard.')
 ->prefix('userdashboard')
 ->group(function(){
     Route::get('/home', HomeController::class)->name('home');
     Route::resource('editUserInfo', UserEditController::class);

 });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','avatar', 'email', 'password','user_name','phone','country','city','state'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use App\Services\FileUploadService;
use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::role('user')->get();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required',
            'user_name' => 'required|unique:users',
            'phone' => 'required',
            'country' => 'required',
            'city' => 'required',
            'state' => 'required',
          ]);
        $file = FileUploadService::upload( $request->file('avatar'), 'public/User' );
        $user = new User;
        $user->name = $request->name;
        $user->avatar =$request->file->uploaded_name;
        $user->email  = $request->email ;
        $user->password = bcrypt($request->password);
        $user->user_name = $request->user_name;
        $user->phone = $request->phone;
        $user->country = $request->country;
        $user->city = $request->city;
        $user->state = $request->state;
        $user->save();

        $user->assignRole('data-entry');
        $request->session()->flash('msg','Record successfully inserted');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=User::find($id);
        return view('admin.user.edit',['user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        if ($request->hasFile('avatar') && $request->file('avatar')) {
            $validateData = $request->validate([

                'email' => ['required',
                    Rule::unique('users')->ignore($id)],
                'user_name' => ['required',
                    Rule::unique('users')->ignore($id)],
                'name' => 'required',
                'phone' => 'required',
                'country' => 'required',
                'city' => 'required',
                'state' => 'required',
              ]);
              $file = FileUploadService::upload( $request->file('avatar'), 'public/User' );
              $user=  User::find($id);
              $user->name = $request->name;
              $user->avatar =$request->file->uploaded_name;
              $user->email  = $request->email ;
              $user->user_name = $request->user_name;
              $user->phone = $request->phone;
              $user->country = $request->country;
              $user->city = $request->city;
              $user->state = $request->state;
              $user->save();

              $request->session()->flash('msg','Record Updated');
              // redirect to home
              return redirect()->route('users.index');

        }else{
            $validateData = $request->validate([

                'email' => ['required',
                    Rule::unique('users')->ignore($id)],
                'user_name' => ['required',
                    Rule::unique('users')->ignore($id)],
                'name' => 'required',
                'phone' => 'required',
                'country' => 'required',
                'city' => 'required',
                'state' => 'required',
              ]);


              $user=  User::find($id);
              $user->name = $request->name;
              $user->avatar =$request->file->uploaded_name;
              $user->email  = $request->email ;
              $user->password = bcrypt($request->password);
              $user->user_name = $request->user_name;
              $user->phone = $request->phone;
              $user->country = $request->country;
              $user->city = $request->city;
              $user->state = $request->state;
              $user->save();

              $request->session()->flash('msg','Record Updated');
              // redirect to home
              return redirect()->route('users.index');
        }





        // message

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::find($id);
        $user->roles()->detach();
        if ($user != null){
            $user->delete();
            session()->flash('msg','User Deleted Successfully');
        }

        return back();
    }
}

resources/views/admin/user/create.blade.php
@extends("layouts.admin.site")
@section("content")
<h4 class="font-weight-bold py-3 mb-4">
    Add User <span class="text-muted"></span>
</h4>

<div class="nav-tabs-top">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#user-edit-account">Account</a>
        </li>

    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="user-edit-account">
            <form method="POST" action="{{ route('users.store') }}" >

                @csrf
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <div class="media align-items-center">
                        <img src="assets/img/avatars/5-small.png" alt="" class="d-block ui-w-80">
                        <div class="media-body ml-3">
                            <label class="form-label d-block mb-2">Avatar</label>
                            <label class="btn btn-outline-primary btn-sm">
                             Add
                            <input type="file" name="avatar" class="user-edit-fileinput">
                            </label>&nbsp;

                        </div>
                    </div>

                </div>
                <hr class="border-light m-0">
                <div class="card-body pb-2">

                    <div class="form-group">
                        <label class="form-label">Username</label>
                        <input type="text" name="user_name" class="form-control mb-1" placeholder="User Name">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Password</label>
                        <input type="password" name="password" class="form-control mb-1" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Name</label>
                        <input type="text" name="name" class="form-control" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <label class="form-label">E-mail</label>
                        <input type="text" name="email" class="form-control mb-1" placeholder="example@exe.com">
                        <a href="javascript:void(0)" class="small">Resend confirmation</a>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Phone</label>
                        <input type="text" name="phone" class="form-control" placeholder="Phone">
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">Country</label>
                                <input type="text" name="country" class="form-control" >
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">City</label>
                                <input type="text" name="city" class="form-control" placeholder="City">
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">State</label>
                                <input type="text" name="state" class="form-control" >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right m-3 px-3">
                    <button type="submit" class="btn btn-primary">Add User</button>&nbsp;
                    <a href="{{ route('users.index') }}" class="btn btn-default">Back</a>
                </div>
            </form>


        </div>
    </div>
</div>

@endsection

resources/views/admin/user/edit.blade.php
@extends("layouts.admin.site")
@section("content")
<h4 class="font-weight-bold py-3 mb-4">
    Edit User <span class="text-muted"></span>
</h4>

<div class="nav-tabs-top">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#user-edit-account">Account</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="user-edit-account">
            <form method="post" action="{{ route('users.update',$user->id) }}">
                @csrf
                @method('put');
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                    <div class="media align-items-center">
                        <img src="assets/img/avatars/5-small.png" alt="" class="d-block ui-w-80">
                        <div class="media-body ml-3">
                            <label class="form-label d-block mb-2">Avatar</label>
                            <label class="btn btn-outline-primary btn-sm">
      Change
      <input type="file"   name="avatar" class="user-edit-fileinput">
    </label>&nbsp;
                            <button type="button" class="btn btn-default btn-sm md-btn-flat">Reset</button>
                        </div>
                    </div>

                </div>
                <hr class="border-light m-0">
                <div class="card-body pb-2">

                    <div class="form-group">
                        <label class="form-label">Username</label>
                        <input type="text" class="form-control mb-1" name="user_name" placeholder="User Name" value="{{ $user->user_name }}">
                    </div>

                    <div class="form-group">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control" name="name" placeholder="Name" value="{{ $user->name }}">
                    </div>
                    <div class="form-group">
                        <label class="form-label">E-mail</label>
                        <input type="text" class="form-control mb-1" name="email" placeholder="example@exe.com" value="{{ $user->email }}">
                        {{-- <a href="javascript:void(0)" class="small">Resend confirmation</a> --}}
                    </div>
                    <div class="form-group">
                        <label class="form-label">Phone</label>
                        <input type="text" class="form-control" name="phone" placeholder="Phone" value="{{ $user->phone }}">
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">Country</label>
                                <input type="text" class="form-control" name="country" placeholder="City" value="{{ $user->country }}">
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">City</label>
                                <input type="text" class="form-control" name="city" placeholder="City" value="{{ $user->city }}">
                            </div>

                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">State</label>
                                <input type="text" class="form-control" name="state" placeholder="state" value="{{ $user->state }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right m-3 px-3">
                    <button type="submit" class="btn btn-primary">Save changes</button>&nbsp;
                    <a href="{{ route('users.index') }}" class="btn btn-default">Back</a>
                </div>
            </form>


        </div>
    </div>
</div>

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin.site')
@section('content')
<h4 class="font-weight-bold py-3 mb-4">
    <span class="text-muted font-weight-light">User </span>
</h4>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('msg') }}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
 </div>
<!-- DataTable within card -->

<div class="card">
     @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<h6 class="card-header text-right">
    <a href="{{ route('users.create') }}" class="btn btn-success" > Add New</a>
</h6>
    <div class="card-datatable table-responsive">
        <table class="datatables-demo table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @isset($users)
                    @if (count($users) > 0)
                        @foreach ($users as $user)
                        <tr class="odd gradeX">
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name  }}</td>
                            <td>{{ $user->email  }}</td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-success dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false">Active</button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: top, left; top: 25px; left: 0px;">
                                        <a class="dropdown-item">Deactivate</a>
                                    </div>
                                </div>
                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-dark dropdown-toggle waves-effect" data-toggle="dropdown" aria-expanded="false">Action</button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: top, left; top: 35px; left: 0px;">
                                        <a href="{{ route('users.show',$user->id) }}" class="dropdown-item"><i class="fa fa-eye"></i> View Profile</a>

                                        {{--  <a href="" class="dropdown-item"><i class="fa fa-plus"></i> Add User </a>  --}}

                                        <a href="{{ route('users.edit',$user->id) }}" class="dropdown-item"><i class="fa fa-edit"></i> Edit </a>
                                        <form action="{{ route('users.destroy',$user->id) }}" class="d-flex" method="post">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="submit" class="dropdown-item">
                                                <i class="fa fa-trash"></i> Delete
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <div class="m-3 text-center col-12">
                            <p>No Organzier found...!</p>
                        </div>
                    @endif
                @endisset


            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends("layouts.admin.site")
@section("content")

<div class="media align-items-center py-3 mb-3">
    <img src="assets/img/avatars/5-small.png" alt="" class="d-block ui-w-100 rounded-circle">
    <div class="media-body ml-4">
        <h4 class="font-weight-bold mb-0">{{ $user->name }}</h4>
        <div class="text-muted mb-2">ID: 3425433</div>
        <a href="{{ route('users.edit',$user->id) }}" class="btn btn-primary btn-sm">Edit</a>&nbsp;
        <a href="javascript:void(0)" class="btn btn-default">Back</a>&nbsp;
        {{--  <a href="javascript:void(0)" class="btn btn-default btn-sm icon-btn"><i class="ion ion-md-mail"></i></a>  --}}
    </div>
</div>


<div class="card">

    <div class="card-body">
        @isset($user)
        <table class="table user-view-table m-0">
            <tbody>
                <tr>
                    <td>Username:</td>
                    <td>{{ $user->user_name }}</td>
                </tr>
                <tr>
                    <td>Name:</td>
                    <td>{{ $user->name }}</td>
                </tr>
                <tr>
                    <td>E-mail:</td>
                    <td>{{ $user->email }}</td>
                </tr>
                <tr>
                    <td>Phone:</td>
                    <td>{{ $user->phone }}</td>
                </tr>
                <tr>
                    <td>Status:</td>
                    <td><span class="badge badge-outline-success">Active</span></td>
                </tr>
                <tr>
                    <td>Country:</td>
                    <td>{{ $user->country }}</td>
                </tr>
                <tr>
                    <td>City:</td>
                    <td>{{ $user->city }}</td>
                </tr>
                <tr>
                    <td>State:</td>
                    <td>{{ $user->state }}</td>
                </tr>
            </tbody>
        </table>

        @endisset
    </div>
</div>
@endsection